# Generated by Django 4.1.4 on 2023-07-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
