# Generated by Django 4.1.4 on 2023-07-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_delete_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_notificacao', models.DateField()),
                ('tipo_teste', models.CharField(max_length=100)),
                ('estado_teste', models.CharField(max_length=100)),
                ('assintomatico', models.BooleanField()),
                ('sintomas', models.CharField(max_length=100)),
                ('condicoes_especiais', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
                ('data_envio', models.DateField()),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.atendimento')),
            ],
        ),
    ]
