# Generated by Django 4.1.4 on 2022-12-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id_atendimento', models.AutoField(primary_key=True, serialize=False)),
                ('estrategia_atendimento', models.CharField(max_length=100)),
                ('local_atendimento', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('cbo', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cor', models.CharField(max_length=20)),
                ('tradicionalidade', models.BooleanField()),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_notificacao', models.DateField()),
                ('tipo_teste', models.CharField(max_length=100)),
                ('estado_teste', models.CharField(max_length=100)),
                ('assintomatico', models.BooleanField()),
                ('sintomas', models.CharField(max_length=100)),
                ('condicoes_especiais', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
                ('data_envio', models.DateField()),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
    ]
