# Generated by Django 4.1.4 on 2023-09-05 16:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='resultado',
            field=models.CharField(choices=[('REAGENTE', 'Resultado positivo'), ('NAO_REAGENTE', 'Resultado negativo'), ('INDETERMINADO', 'Resultado indeterminado')], max_length=128, null=True),
        ),
    ]
