# Generated by Django 4.0.3 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_bairro_descricao_alter_cidade_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='local_atendimento',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='id_atendimento',
            new_name='atendimento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='id_atendimento',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='id_notificacao',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
