# Generated by Django 4.1.4 on 2023-07-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_unidadebasica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.unidadebasica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cbo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
