# Generated by Django 4.0.3 on 2023-07-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_atendimento_local_alter_paciente_cbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='resultado',
            field=models.CharField(default='INDETERMINADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadebasica',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='web.cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadebasica',
            name='descricao',
            field=models.CharField(default='Não Informado', max_length=128, verbose_name='Unidade basica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cor',
            field=models.CharField(choices=[('BRAN', 'Branco'), ('PARD', 'Pardo'), ('AMARELO', 'Amarelo'), ('PRETO', 'Preto'), ('INDIGINA', 'Indígina'), ('IGNORADO', 'Ignorado')], max_length=20),
        ),
    ]
