# Generated by Django 4.1.4 on 2023-07-19 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_notificacao_resultado_unidadebasica_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='descricao',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_notificacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
