# Generated by Django 4.1.4 on 2023-07-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_atendimento_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='web.cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='estado_teste',
            field=models.CharField(choices=[('SOLICITADO', 'Teste solicitado'), ('COLETADO', 'Teste coletado'), ('CONCLUIDO', 'Teste concluido'), ('NAO_SOLICITADO', 'Teste não solicitado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='resultado',
            field=models.CharField(choices=[('REAGENTE', 'Resultado positivo'), ('NAO_REAGENTE', 'Resultado negativo'), ('INDETERMINADO', 'Resultado indeterminado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_teste',
            field=models.CharField(choices=[('RT-QCPR', 'Teste molecular em tempo real - RT-PCR'), ('RT-LAMP', 'Teste molecular de amplianção isotermica - RT-LAMP'), ('ANTIGENO', 'Teste rapido com Aitígeno')], max_length=100),
        ),
    ]
