# Generated by Django 4.1.4 on 2023-07-19 20:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_paciente_cidade_alter_notificacao_estado_teste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='condicoes_especiais',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sintomas',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cbo',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date.today), django.core.validators.MinValueValidator(1999)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone1',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='unidadebasica',
            name='descricao',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Unidade basica'),
        ),
    ]
