# Generated by Django 4.1.4 on 2023-07-19 20:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_notificacao_condicoes_especiais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='estrategia_atendimento',
            field=models.CharField(choices=[('DIAGNOSTICO_SINTOMATICO', 'Diagnóstico assistencial'), ('BUSCA_ATIVA_ASSINTOMATICO', 'Busca ativa de assintomático'), ('TRIAGEM_POPULACAO_ESPECIFICA', 'Triagem de população específica')], max_length=128),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='assintomatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='estado_teste',
            field=models.CharField(choices=[('SOLICITADO', 'Teste solicitado'), ('COLETADO', 'Teste coletado'), ('CONCLUIDO', 'Teste concluido'), ('NAO_SOLICITADO', 'Teste não solicitado')], max_length=128),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='resultado',
            field=models.CharField(choices=[('REAGENTE', 'Resultado positivo'), ('NAO_REAGENTE', 'Resultado negativo'), ('INDETERMINADO', 'Resultado indeterminado')], max_length=128),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_teste',
            field=models.CharField(choices=[('RT-QCPR', 'Teste molecular em tempo real - RT-PCR'), ('RT-LAMP', 'Teste molecular de amplianção isotermica - RT-LAMP'), ('ANTIGENO', 'Teste rapido com Aitígeno')], max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tradicionalidade',
            field=models.BooleanField(default=False),
        ),
    ]
