# Generated by Django 4.1.4 on 2023-08-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_atendimento_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='condicoes_especiais',
            field=models.CharField(blank=True, choices=[('DOENCA_RESPIRATORIA', 'Doenças respiratória crônica'), ('DOENCA_RENAL', 'Doenças renal crônica em estagio avançado'), ('DOENCA_CROMOSSOMICA', 'Doenças cromossômicas ou estado de fragilidade imunológica'), ('DOENCA_CARDIOVASCULAR', 'Doença cardíacas crônicas'), ('DOENCA_PUERPERA', 'Puérpera (até 45 dias do parto)'), ('IMUNOSSUPRESSAO', 'Imunossupressão'), ('DIABETES', 'Diabetes'), ('GESTANTE', 'Gestante'), ('OBESIDADE', 'Obesidade'), ('OUTROS', 'Outros')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sintomas',
            field=models.CharField(blank=True, choices=[('CORIZA', 'Coriza'), ('FEBRE', 'Febre'), ('DOR_DE_CABECA', 'Dor de cabeça'), ('DOR_GARGANTA', 'Dor de garganta'), ('DISTURBIOS_GUSTATIVOS', 'Distúrbios gustativos'), ('DISPNEIA', 'Dispneia'), ('DISTURBIOS_OLFATIVOS', 'Distúrbios olfativos'), ('TOSSE', 'Tosse'), ('OUTROS', 'Outros')], max_length=256, null=True),
        ),
    ]
