# Generated by Django 4.1.4 on 2023-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_notificacao_condicoes_especiais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='condicoes_especiais',
        ),
    ]
