# Generated by Django 4.1.4 on 2023-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_notificacao_condicoes_especiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='condicoes_especiais',
            field=models.CharField(blank=True, choices=[('DOENCA_RESPIRATORIA', 'Doenças respiratória crônica'), ('DOENCA_RENAL', 'Doenças renal crônica em estagio avançado'), ('DOENCA_CROMOSSOMICA', 'Doenças cromossômicas ou estado de fragilidade imunológica'), ('DOENCA_CARDIOVASCULAR', 'Doença cardíacas crônicas'), ('DOENCA_PUERPERA', 'Puérpera (até 45 dias do parto)'), ('IMUNOSSUPRESSAO', 'Imunossupressão'), ('DIABETES', 'Diabetes'), ('GESTANTE', 'Gestante'), ('OBESIDADE', 'Obesidade'), ('OUTROS', 'Outros')], max_length=256, null=True),
        ),
    ]
