# Generated by Django 4.1.4 on 2023-08-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_notificacao_condicoes_especiais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='sintomas',
            field=models.CharField(choices=[('CORIZA', 'Coriza'), ('FEBRE', 'Febre'), ('DOR_DE_CABECA', 'Dor de cabeça'), ('DOR_GARGANTA', 'Dor de garganta'), ('DISTURBIOS_GUSTATIVOS', 'Distúrbios gustativos'), ('DISPNEIA', 'Dispneia'), ('DISTURBIOS_OLFATIVOS', 'Distúrbios olfativos'), ('TOSSE', 'Tosse'), ('OUTROS', 'Outros')], default=1, max_length=256, null=True),
        ),
    ]
