# Generated by Django 4.1.4 on 2023-09-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_notificacao_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='condicoes_especiais',
            field=models.CharField(max_length=256, null=True, verbose_name='Condições Especiais'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sintomas',
            field=models.CharField(choices=[('CORIZA', 'Coriza'), ('FEBRE', 'Febre'), ('DOR_DE_CABECA', 'Dor de cabeça'), ('DOR_GARGANTA', 'Dor de garganta'), ('DISTURBIOS_GUSTATIVOS', 'Distúrbios gustativos'), ('DISPNEIA', 'Dispneia'), ('DISTURBIOS_OLFATIVOS', 'Distúrbios olfativos'), ('TOSSE', 'Tosse'), ('OUTROS', 'Outros')], max_length=256, null=True, verbose_name='Sintomas'),
        ),
    ]
