# Generated by Django 4.1.4 on 2023-09-05 15:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_notificacao_condicoes_especiais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='sintomas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CORIZA', 'Coriza'), ('FEBRE', 'Febre'), ('DOR_DE_CABECA', 'Dor de cabeça'), ('DOR_GARGANTA', 'Dor de garganta'), ('DISTURBIOS_GUSTATIVOS', 'Distúrbios gustativos'), ('DISPNEIA', 'Dispneia'), ('DISTURBIOS_OLFATIVOS', 'Distúrbios olfativos'), ('TOSSE', 'Tosse'), ('OUTROS', 'Outros')], max_length=250, null=True, verbose_name='Sintomas'),
        ),
    ]
